### PR TITLE
Add examples folder

### PR DESCRIPTION
**Pull request by nhducit**

### CODE REVIEW

**Comment by nhducit** [comment]
@avigoldman Can you help me review this PR.

**Comment by avigoldman** [comment]
Hey sorry I missed this 👋 

This all looks good. I think that we should also start at V2 since we might be able to a more "natural" integration between MDX and GatsbyJS. Maybe even making exported variables from MDX files queryable through GraphQL.

**Comment by nhducit** [comment]
@avigoldman do you mean gatsby v2?

**Comment by avigoldman** [comment]
Yup 😬

**Comment by nhducit** [comment]
@avigoldman I agree, but I haven't try gatsby V2 yet. Have you tried V2?
btw. I invited you as collaborators

**Pull request merged**
